### ISSUE TITLE
vite-plugin-vue2 安装失败

### ISSUE THREAD

**Issue by xcsweb** [underfin/vite-plugin-vue2#10]
vite-plugin-vue2 
![image](https://user-images.githubusercontent.com/20693737/99328971-27196000-28b8-11eb-9fbf-0fbc9dfcde17.png)，经常到了最后一步就不动了

**Comment by underfin** [comment]
Can you install `vite` before? Maybe it caused by `esbuild` need connect to `https://registry.npmjs.org`

**Comment by underfin** [comment]
Close it because not response
