### ISSUE TITLE
How to enable runtime compiler?

### ISSUE THREAD

**Issue by Thomasan1999** [underfin/vite-plugin-vue2#100]
I'm using components which are sent from API and loaded from `Vue.component()`, so I need a runtime compiler for that. With Webpack, I could use the option `runtimeCompiler: true`. Can I achieve the same thing with this plugin?

**Comment by underfin** [comment]
Please see https://vuejs.org/v2/guide/installation.html#Runtime-Compiler-vs-Runtime-only, you can config `alias` to use vue-core with compiler.
