### ISSUE TITLE
The css code is exist in js bundle

### ISSUE THREAD

**Issue by 869288142** [underfin/vite-plugin-vue2#101]
* Problem
I found that the js bundle contains css files

*  Reproduction Step

  1. yarn create @vitejs/app
  2. check vue template
  3. replace  @vitejs/plugin-vue for  vite-plugin-vue2
  4. yarn build
  5. check dist/asset/index.js
  6. you can find css in js bundle
 
**Looks like a plug-in issue， i need some help**

**Comment by screetBloom** [comment]
If you are using vite-plugin-vue2 in vue2

I recommend using vue cli for the build of the production environment

**Comment by zhanglolo** [comment]
这个是`vite`的特性吧。

官方文档有描述：
> Importing .css files will inject its content to the page via a <style> tag with HMR support. You can also retrieve the processed CSS as a string as the module's default export.
导入 .css 文件将会把内容插入到 <style> 标签中，同时也带有 HMR 支持。也能够以字符串的形式检索处理后的、作为其模块默认导出的 CSS。

**Comment by 869288142** [comment]
> 这个是`vite`的特性吧。
> 
> 官方文档有描述：
> 
> > Importing .css files will inject its content to the page via a <style> tag with HMR support. You can also retrieve the processed CSS as a string as the module's default export.
> > 导入 .css 文件将会把内容插入到 <style> 标签中，同时也带有 HMR 支持。也能够以字符串的形式检索处理后的、作为其模块默认导出的 CSS。

这两者没关系哈，你用vue3就不会出现这个问题

**Comment by zhanglolo** [comment]
和这个问题类似吗？ https://github.com/vitejs/vite/issues/4764

**Comment by 869288142** [comment]
> 和这个问题类似吗？ [vitejs/vite#4764](https://github.com/vitejs/vite/issues/4764)

vite use terser tree-shaking unsed code, the issue behavior is correct.  esbuild don't have tree-shaking Ability

**Comment by jerryYuX** [comment]
> > 和这个问题类似吗？ [vitejs/vite#4764](https://github.com/vitejs/vite/issues/4764)
> 
> vite use terser tree-shaking unsed code, the issue behavior is correct. esbuild don't have tree-shaking ability

esbuild  have tree-shaking ability,see [evanw/esbuild#1576](https://github.com/evanw/esbuild/issues/1576)

**Comment by 869288142** [comment]
> > > 和这个问题类似吗？ [vitejs/vite#4764](https://github.com/vitejs/vite/issues/4764)
> > 
> > 
> > vite use terser tree-shaking unsed code, the issue behavior is correct. esbuild don't have tree-shaking ability
> 
> esbuild have tree-shaking ability,see [evanw/esbuild#1576](https://github.com/evanw/esbuild/issues/1576)

The issiue has nothing to do with tree-shaking. it is hack that we can extern css.  but esbuild transform API not provide unsed option  that it is confused

**Comment by 869288142** [comment]
This is a problem with vite. it was [fixed](https://github.com/vitejs/vite/pull/5041#issue-1004938117)

**Comment by 869288142** [comment]
This is a problem with vite. it was [fixed](https://github.com/vitejs/vite/pull/5041#issue-1004938117)
