### ISSUE TITLE
Typescript type checking

### ISSUE THREAD

**Issue by stephantabor** [underfin/vite-plugin-vue2#102]
Is there a way to get type checking at the CLI when using vite with this plugin? I've migrated a project from vue-cli, which would do the type checking during the `build` process, and just noticed that this one does not because I found several type errors in that got checked into our project :(

**Comment by underfin** [comment]
The typing check will not supported, you can use some tools do this, like https://github.com/vuejs/vetur.

**Comment by stephantabor** [comment]
That doesn't seem to be in any way a replacement for type checking your project when you build it. It only has unstable WIP support for type checking in templates, which is not the behavior from vue-cli that I'm trying to achieve. 

I'll have to go back to vue-cli if typescript support is not a goal of this project.
