### ISSUE TITLE
using decorator in tsx error

### ISSUE THREAD

**Issue by freeozyl80** [underfin/vite-plugin-vue2#106]
![image](https://user-images.githubusercontent.com/8967606/125179215-0f179780-e21f-11eb-8513-5145f1c4cd51.png)
![image](https://user-images.githubusercontent.com/8967606/125179221-26568500-e21f-11eb-8058-ebc7330986d8.png)
![image](https://user-images.githubusercontent.com/8967606/125179226-38382800-e21f-11eb-98d1-3f8f424922b7.png)

**Comment by pedro-gilmora** [comment]
@underfin I found the solution for this. You should allow `.babelrc` config

Left is the original, right the modifications
![image](https://user-images.githubusercontent.com/33942331/125448482-e6a1e49c-bb34-4ebc-a371-5e1bf9e7b853.png)

So, to solve problems with .babelrc
![image](https://user-images.githubusercontent.com/33942331/125448816-18c57b8c-b662-4fef-b2d9-c711f0d9a7ec.png)

**Comment by ChesterBu** [comment]
i have the same problem

**Comment by 251205668** [comment]
![image](https://user-images.githubusercontent.com/46418596/126425137-a5c922b7-57b9-469d-8c60-10c9eb5758e2.png)

![image](https://user-images.githubusercontent.com/46418596/126425185-76070d40-525f-47ad-8086-063d71c3ae6e.png)

I have set up babel, why is it still reporting an error @pedro-gilmora 。

**Comment by 251205668** [comment]
@freeozyl80 How did you solve this problem？

**Comment by pedro-gilmora** [comment]
> ![image](https://user-images.githubusercontent.com/46418596/126425137-a5c922b7-57b9-469d-8c60-10c9eb5758e2.png)
> 
> ![image](https://user-images.githubusercontent.com/46418596/126425185-76070d40-525f-47ad-8086-063d71c3ae6e.png)
> 
> I have set up babel, why is it still reporting an error @pedro-gilmora 。

I solved as my comment shows

**Comment by zqcccc** [comment]
> @underfin I found the solution for this. You should allow `.babelrc` config
> 
> Left is the original, right the modifications
> ![image](https://user-images.githubusercontent.com/33942331/125448482-e6a1e49c-bb34-4ebc-a371-5e1bf9e7b853.png)
> 
> So, to solve problems with .babelrc
> ![image](https://user-images.githubusercontent.com/33942331/125448816-18c57b8c-b662-4fef-b2d9-c711f0d9a7ec.png)

It looks like you've changed the `node_modules/vite-plugin-vue2/dist/jsxTransform.js` file, which doesn't seem like the right thing to do in a multi-person collaboration situation

**Comment by underfin** [comment]
close at https://github.com/underfin/vite-plugin-vue2/commit/08821c6457ad22afd11e86d3fa118bc3c7ca7e25

**Comment by pedro-gilmora** [comment]
> > @underfin I found the solution for this. You should allow `.babelrc` config
> > Left is the original, right the modifications
> > ![image](https://user-images.githubusercontent.com/33942331/125448482-e6a1e49c-bb34-4ebc-a371-5e1bf9e7b853.png)
> > So, to solve problems with .babelrc
> > ![image](https://user-images.githubusercontent.com/33942331/125448816-18c57b8c-b662-4fef-b2d9-c711f0d9a7ec.png)
> 
> It looks like you've changed the `node_modules/vite-plugin-vue2/dist/jsxTransform.js` file, which doesn't seem like the right thing to do in a multi-person collaboration situation

of course it was a proposal I didn't say to anyone to apply qhat I did, I just told to @underfin  to put an eye  on this solution
