### ISSUE TITLE
Error when importing types that shadow built-in values

### ISSUE THREAD

**Issue by micgro42** [underfin/vite-plugin-vue2#108]
_vite_ fails on the code below with an error message like `No matching export in "src/Error.ts" for import "default"`. _vue-cli_ can handle it just fine.

**Error.ts:**
```ts
interface Error {
  message: string;
}
export default Error;
```

**main.ts**:
```ts
import Error from '@/Error';

function getError(): Error {
  if ( somethingIsWrong() ) {
    throw new Error('I\'m a native javascript Error!');
  }

  return { message: 'I\'m the expected custom error object.' };
}
```

A minimal repo to reproduce is issue: https://github.com/micgro42/vite-type-shadowing-bug/

This was found while migrating a vue 2 project from vue-cli to vite. So, I _assume_ that it might be a problem with this plugin, but it might just as well be a problem with vite itself. If that is the case, then please let me know, and I'll reopen this issue there.

Please let me know if you have any further questions, I'm happy to help.

**Comment by screetBloom** [comment]
``` code
- import Error from "@/data-model/Error";
+ import type Error from "@/data-model/Error";
```

like this 👇
![image](https://user-images.githubusercontent.com/22092110/128627117-d5840bb0-8b47-4060-97d1-a79ef7afbd23.png)

**Comment by underfin** [comment]
Sorry for later feedback.This is caused by esbuild compile single ts file and it lose the context with other files types. You can resolve it like @screetBloom said.

**Comment by micgro42** [comment]
Mh, interesting. Thank you both! :pray:
