### ISSUE TITLE
Help configure runtime template compiler

### ISSUE THREAD

**Issue by imoldfella** [underfin/vite-plugin-vue2#111]
I need it for vue vega. Thank you for this tool, but now I don't think I can go back to life before vite. But I can't figure out how to get vue 2 with the run time template compiler. The answers I've been able to google seem to apply only to webpack.

**Comment by screetBloom** [comment]
It's hard to know exactly what the problem is with such a description

Can u provide a mini repo?

**Comment by underfin** [comment]
@imoldfella you can add blew configure to `vite.config.js`.
```
resolve: {
    alias: {
      'vue': require.resolve('vue/dist/vue.js'),
    },
  },
```

**Comment by fyzhu** [comment]
> resolve: {
>     alias: {
>       'vue': require.resolve('vue/dist/vue.js'),
>     },
>   },

How about putting this config in README.md?

**Comment by OleksandrSymonov** [comment]
Hope it will be helpful
`
  resolve: {
    alias: [
      ...
      // Runtime compiler enable
      {
        find: "vue",
        replacement: require.resolve("vue/dist/vue.js"),
      },
    ],
  },
`
