### ISSUE TITLE
losing esbuild param:'target' when transform script tag in .vue files

### ISSUE THREAD

**Issue by DarkKris** [underfin/vite-plugin-vue2#112]
Hello!

I'm trying to transform ES version of .vue files when vite serve mode, **even through it will cause performance reducing**.
But I found that the params 'target' of func 'transformWithEsbuild' is losing.

![image](https://user-images.githubusercontent.com/21234945/127102287-3b6edfbd-ad00-4bd9-b1f8-58bd1c5a64c9.png)

Will it support in the future that allowing syntax conversions? It's important to me.

like that:

```js
// vite.config.ts
...
plugins: [
    createVuePlugin({
        target: 'es6'
    });
],
...

// vite-plugin-vue2/dist/main.js

async function genScriptCode(...) {
...
if (script.lang === "ts") {
    const result = await options.devServer.transformWithEsbuild(scriptCode, filename, { loader: 'ts', ...options }, map);
}
...
}
```

**Comment by underfin** [comment]
You can use `esbuild` options to do it, like below. 
```
{
      esbuild: {
           target: 'xxx'
      }
}
```

Doc is here. https://vitejs.dev/config/#esbuild
