### ISSUE TITLE
Not working with classes

### ISSUE THREAD

**Issue by shadow-light** [underfin/vite-plugin-vue2#119]
I can't get this plugin to work with classes. It seems like this issue was [resolved earlier](https://github.com/underfin/vite-plugin-vue2/issues/28), so I'm not sure what's going on.

Sample component:

```
<script lang='ts'>

import {Component, Vue} from 'vue-property-decorator'

@Component({})
export default class extends Vue {}

</script>
```

Console error:

```
11:06:32 PM [vite] Internal server error: Transform failed with 1 error:
.../src/components/routes/RouteInvalid.vue:17:6: error: Expected identifier but found "extends"
  Plugin: vite-plugin-vue2
  File: .../src/components/routes/RouteInvalid.vue
  
  Expected identifier but found "extends"
  15 |  
  16 |  @Component({})
  17 |  class extends Vue {}
     |        ^
  18 |  
  19 |  
  
      at failureErrorWithLog (.../node_modules/esbuild/lib/main.js:1449:15)
      at .../node_modules/esbuild/lib/main.js:1260:29
      at .../node_modules/esbuild/lib/main.js:609:9
      at handleIncomingPacket (.../node_modules/esbuild/lib/main.js:706:9)
      at Socket.readFromStdout (.../node_modules/esbuild/lib/main.js:576:7)
      at Socket.emit (events.js:315:20)
      at Socket.EventEmitter.emit (domain.js:485:12)
      at addChunk (_stream_readable.js:297:12)
      at readableAddChunk (_stream_readable.js:273:9)
      at Socket.Readable.push (_stream_readable.js:214:10)
      at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)

```
Versions:

```
    vite: 2.4.4 
    vite-plugin-vue2: 1.8.0 
```

**Comment by shadow-light** [comment]
I worked out something that seems to fix. Referring to the [original PR](https://github.com/underfin/vite-plugin-vue2/pull/29/files)...

`const exportDefaultClassRE = /export\s+default\s+class\s+([\w$]+)/` seems to be trying to get the name of the class, but in my case it has no name, and instead obtains "extends Vue"

So obviously things go wrong here when `$1` is "extends Vue"

```
        scriptCode = `${script.content.replace(
          exportDefaultClassRE,
          `class $1`
        )}\nconst ${scriptVar} = ${classMatch[1]}`
```

So instead I manually just set an arbitrary name and it seems to then work and build fine.

```
        scriptCode = `${script.content.replace(
          exportDefaultClassRE,
          `class NAME $1`
        )}\nconst ${scriptVar} = NAME`
```

Any idea on how to fix this in a way that works for everyone's situations?

**Comment by shadow-light** [comment]
For anyone else affected by this, here's a plugin that fixes the issue. Just import and add to plugins in vite config.

```javascript
// Vite plugin that corrects definition of nameless classes
// See https://github.com/underfin/vite-plugin-vue2/issues/119

export default function(){

    return {
        name: 'nameless-classes',

        transform(code, id){

            if (!id.endsWith('.vue')){
                return null  // Only applicable to regular vue file imports
            }

            return code.replace('export default class extends Vue',
                'export default class ViteNamelessPluginClass extends Vue')
        }
    }
}
```
Still a bit hacky, so an official solution is still desirable.

**Comment by zqcccc** [comment]
You should give the class name
```js
export default class Foo extends Vue {}
```

**Comment by shadow-light** [comment]
Yes seems like that's expected, but I never had an issue with it up till now. And the plugin above conveniently sets the class name from the file name, which in my case is always identical. I don't think the build should fail due to missing class name though. There's no practical reason why it should, and didn't with Webpack before.

**Comment by underfin** [comment]
This is not valid js synax, so the esbuild give error for this. Please changed your code for this.

**Comment by shadow-light** [comment]
My scripts are valid syntax though. The following runs fine in Chrome without any bundler:

```html
<!DOCTYPE html>
<html>
<body>
    <script type='module'>
        import nameless from './module.js'
        new nameless().hello()
    </script>
</body>
</html>
```

```js
class Something {
}

export default class extends Something {
    hello(){
        console.log('Hello')
    }
}
```

The problem is the syntax becomes invalid because this plugin has to mutate the code to make it work with Vite. But that mutation currently turns valid JS into invalid JS, from `export default class extends Vue` to `class extends Vue`.
