### ISSUE TITLE
how to import .vue files from node_modules

### ISSUE THREAD

**Issue by rhinonan** [underfin/vite-plugin-vue2#126]
I need import some .vue files from node_modules.

```ts
import CloudsecTopNav from '@sxf/cloudsec-components/src/packages/top-nav/index.vue';
```

but I got error
```shell
 [vite] Internal server error: Failed to resolve entry for package "D:\Code\xsec\ui\node_modules\@sxf\cloudsec-components\src\packages\alarm". The package may have incorrect main/module/exports specified in its package.json.
  Plugin: vite:import-analysis
  File: D:/Code/xsec/ui/node_modules/@sxf/cloudsec-components/src/packages/top-nav/index.vue
```

I was use vue-cli before. In vue-cli , we can use `transpileDependencies: ['@sxf/cloudsec-components']`。

So, how can i import .vue files from node_modules with `vite-plugin-vue2` or `vite`?

**Comment by antfu** [comment]
In your `@sxf/cloudsec-components`, you should define 

```json
exports: {
  "./*": "./*"
}
```

in your `package.json` to expose the nested files.

**Comment by screetBloom** [comment]
> ```json
> exports: {
>   "./*": "./*"
> }
> ```


genius!!!  🎉🎉🎉

@antfu   Can you explain why this would work?

**Comment by screetBloom** [comment]
I finally solved my problem with `@originjs/vite-plugin-commonjs`, you can try it

@rhinonan
