### ISSUE TITLE
Can support single tag writing in JSX ?

### ISSUE THREAD

**Issue by HenryNer** [underfin/vite-plugin-vue2#157]
For example, use components like this `render(h) { return <Button />}`,  vite will report the follow error: 
![image](https://user-images.githubusercontent.com/52622417/146506001-2026ffa6-13a6-4c87-b056-7b6173033969.png)

How do i configure it ?

**Comment by woyehaizaixiang** [comment]
> For example, use components like this `render(h) { return <Button />}`, vite will report the follow error: ![image](https://user-images.githubusercontent.com/52622417/146506001-2026ffa6-13a6-4c87-b056-7b6173033969.png)
> 
> How do i configure it ?

<script lang="jsx">
or
<script lang="tsx">
