### ISSUE TITLE
Why is the jsx feature using the antiquated vue jsx preset?

### ISSUE THREAD

**Issue by Aaron-Pool** [underfin/vite-plugin-vue2#17]
I noticed that, if jsx is set to true, this plugin uses the original (babel 6 targeted) vue jsx plugin rather than the [the vue/jsx monorepo package](https://github.com/vuejs/jsx) which targets babel 7, is actively maintained by several core members of the vue team, and even supports several of the latest features of the vue eco system, like the composition api plugin. It also defines a more "vue-like" approach to things like core built in directives (vModel, vOn, etc).

Was this an intentional decision made so that babel 6 would be supported? Or just an oversight?

**Comment by underfin** [comment]
Ah. Just notice that. It should use  as your said. I will work on it.
