### ISSUE TITLE
not working with vitepress

### ISSUE THREAD

**Issue by cloydlau** [underfin/vite-plugin-vue2#18]
It throws an error below in vitepress.

```
runtime-core.esm-bundler.js [Vue warn]: Component is missing template or render function. 
  at <Layout> 
  at <VitePressApp>
```

Thanks for the work. This plugin works fine in vite, would it be considered to support vitepress as well?

Versions:
- vite: 2.0.0-beta.22
- vitepress: 0.10.8
- vite-plugin-vue2: 1.0.2
- vue: 2.6.12

**Comment by underfin** [comment]
`Vitepress` only support vue3.0. You shouldn't use this plugin.
