### ISSUE TITLE
support vite@3.x ?

### ISSUE THREAD

**Issue by kjanusz** [underfin/vite-plugin-vue2#203]
Will the vite-plugin-vue2 also support Vite 3 in the future?

**Comment by laurens94** [comment]
I just added a PR for this: https://github.com/underfin/vite-plugin-vue2/pull/204

**Comment by laurens94** [comment]
Ah it seems it requires more work to be able to function properly with Vite 3 :( Then we'll have to wait with upgrading I guess..

**Comment by khalwat** [comment]
Looking forward to this as well
