### ISSUE TITLE
element-ui 的组件 tooltip无法使用

### ISSUE THREAD

**Issue by 18610509683** [underfin/vite-plugin-vue2#215]
element-ui 的组件 tooltip无法使用，貌似样式都没加载出来

**Comment by antfu** [comment]
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)
