### ISSUE TITLE
SyntaxError: Missing initializer in const declaration

### ISSUE THREAD

**Issue by seanblanchfield** [underfin/vite-plugin-vue2#22]
I have some Vue components that extend another component to override some methods, and therefore don't have their own `<template>` section in the relevant SFC. This caused the above error, due to the following generated code in the corresponding generated file loaded by the browser:

``` javascript
const render, staticRenderFns
```
I made a lucky guess that this was to do with there not being a template section in the file, so I added an empty 
``` html
<template></template>
```
at the top of the file, and the problem went away.

This is a good enough solution for me, but I suggest that the situation where there is no `<template>` should be permitted (as with webpack vue-loader), or a suitable error should be thrown. It is not good that invalid javascript is generated and sent to the browser

Thanks for the great work.

**Comment by andreitere** [comment]
I can confirm this. Using a lot of mixins and each of them fail with the mentioned error.

**Comment by underfin** [comment]
Close at https://github.com/underfin/vite-plugin-vue2/pull/19
