### ISSUE TITLE
ElementUI doesn't work.

### ISSUE THREAD

**Issue by wxs77577** [underfin/vite-plugin-vue2#30]
https://codepen.io/wxs77577/pen/VwmYXxj

`el-button` works well, but the `el-table` doesn't work. But it works in `vue-cli` and codepen.

```html
    <el-button type="primary">Test Button</el-button>

    <el-table :data="[{name:'user1'},{name:'user2'}]">
      <el-table-column label="Name" prop="name"> </el-table-column>
    </el-table>
```

**Comment by wxs77577** [comment]
![image](https://user-images.githubusercontent.com/1990059/106408721-f047f480-6479-11eb-9584-56eabdb090d2.png)

**Comment by underfin** [comment]
It works for me. Can you give an reproduction?

**Comment by wxs77577** [comment]
Sorry, it works in my new project.
