### ISSUE TITLE
Why I used it, get error ...

### ISSUE THREAD

**Issue by gxlself** [underfin/vite-plugin-vue2#33]
![image](https://user-images.githubusercontent.com/32733844/107135471-f5071f80-6935-11eb-927a-3bc779902768.png)

![image](https://user-images.githubusercontent.com/32733844/107136308-d8221a80-693c-11eb-8b53-4bbe9bf74837.png)

package.json dependencies is hidden vue@2.6.12. because it be error...
```json
// package.json
{
  "name": "vite-vue2",
  "version": "0.0.0",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "serve": "vite preview"
  },
  "dependencies": {
  },
  "devDependencies": {
    "vite": "^1.0.0-rc.13",
    "vite-plugin-vue2": "^1.2.0"
  }
}
```

```js
// main.js
import Vue from 'vue'
import App from './App.vue'

Vue.config.productionTip = false

new Vue({
  render: h => h(App)
}).$mount('#app')
```

```js
// vite.config.js 
import { resolve } from "path"
const { createVuePlugin } = require('vite-plugin-vue2')

export default {
  alias: {
    'vue': resolve(__dirname, 'node_modules/vue/dist/vue.esm.browser.js')
  },
  plugins: [createVuePlugin()]
}

```

Please~

**Comment by underfin** [comment]
Look like the your node_modules is not flated after installed. The `vue` should at `vite-plugin-vue2` folder. You can use `path.resolve(path.dirname(require.resolve('vue')), './vue.esm.browser.js')` to have a try.
