### ISSUE TITLE
How to support pug?

### ISSUE THREAD

**Issue by DZLiao** [underfin/vite-plugin-vue2#35]
Is it possible to support pug in vue file <template lang="pug"> and workable? I had tried to install pug and got an error message "Internal server error: Component template requires a root element, rather than just text.", Thank You.

**Comment by underfin** [comment]
You can use like this and installed `pug`.
```
export default {
  plugins: [createVuePlugin({ vueTemplateOptions: { preprocessLang: 'pug' } })],
};
```

**Comment by DZLiao** [comment]
Thanks for the response, after the test and failure, the error message shown

[Vue warn]: Failed to mount component: template or render function not defined.
found in
---> <Anonymous>
       <Root>

Can someone help me, what happened and how to fix it? Thank you.

**Comment by DZLiao** [comment]
> Thanks for the response, after the test and failure, the error message shown
> 
> [Vue warn]: Failed to mount component: template or render function not defined.
> found in
> --->
> Can someone help me, what happened and how to fix it? Thank you.

After remove "createVuePlugin({jsx: false})" from config, it can work.

**Comment by underfin** [comment]
Can you give a reproduction for this?
