### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by johnfumaster** [underfin/vite-plugin-vue2#39]
I can't figure out how to use this plugin.  After installing vite via `npm init @vitejs/app my-vue-app -- --template vue-ts`. I'm lost on what to do next. 

I followed the instructions in the README here, but it doesn't really do it?

Can you outline the steps in more detail please?

**Comment by underfin** [comment]
The `npm init @vitejs/app my-vue-app -- --template vue-ts` will generate project with vue3. If you want use vue@2.x, please installed vue@2.x before use this plugin.

**Comment by pat123456** [comment]
Hi,
Can you please explain how to uninstall vue3 and reinstall vue2 after a fresh install of vite/vue template ?
