### ISSUE TITLE
can i support old project(vue2-webpack)

### ISSUE THREAD

**Issue by andy00614** [underfin/vite-plugin-vue2#41]
i want to upgrade my project(vue2-webpack) using vite.
when i first try, can't run with it
so, i want to know , whether using vite with vite-plugin-vue2 can support my project.
thank you very much!

**Comment by underfin** [comment]
> when i first try, can't run with it

That should work for client bootstrap. If not work, please give me some logs or other somethings to let me check it.

**Comment by webdevomandam** [comment]
tried on old and fresh vue project, doesn't work either

**Comment by lceric** [comment]
I am now using this library to implement vite development for vue2.

- scss var inject
- alias
- cdn script, configure resolve externals
- html ejs

[https://github.com/lceric/vite-vue2-demo](https://github.com/lceric/vite-vue2-demo)

**Comment by underfin** [comment]
@webdevomandam . The `vite-plugin-vue2` is a plguin for `vite`, you should install `vite`.

**Comment by IndexXuan** [comment]
@andy00614 @webdevomandam @lceric 
https://github.com/IndexXuan/vue-cli-plugin-vite

**Comment by underfin** [comment]
Close it becuase not get feedback too long.
