### ISSUE TITLE
dependencies question

### ISSUE THREAD

**Issue by JInann** [underfin/vite-plugin-vue2#45]
in package.json
![image](https://user-images.githubusercontent.com/27847677/108968501-d043d380-76bb-11eb-9381-982cf813a8f5.png)
but，in compiler-sfc/package.json
![image](https://user-images.githubusercontent.com/27847677/108968698-10a35180-76bc-11eb-8a12-d60dc2ad9340.png)
so , run `npm i` in a using 'vite-plugin-vue2' project
```
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: vue@2.6.12
npm WARN node_modules/vue
npm WARN   vue@"^2.6.12" from the root project
npm WARN   1 more (vite-plugin-vue2)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer vue@"3.0.5" from @vue/compiler-sfc@3.0.5
npm WARN node_modules/@vue/compiler-sfc
npm WARN   @vue/compiler-sfc@"^3.0.0-rc.5" from vite-plugin-vue2@1.2.1
npm WARN   node_modules/vite-plugin-vue2
npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
```

**Comment by underfin** [comment]
You should uninstall `@vue/compiler-sfc`. It is is work for vue3. The `vite-plugin-vue2` has own internel `compiler-sfc` logic.

**Comment by xsbchen** [comment]
@underfin `vite-plugin-vue2` requires `@vue/compiler-sfc`
![image](https://user-images.githubusercontent.com/1160705/110751103-5ea08380-827e-11eb-9461-c6fa2d20791a.png)
[see here](https://github.com/underfin/vite-plugin-vue2/blob/master/package.json#L48)
