### ISSUE TITLE
lang="pug" not working in template

### ISSUE THREAD

**Issue by AKamion** [underfin/vite-plugin-vue2#46]
I use  lang="pug" in my template. But it is not work.
`<template lang="pug">
  p index
</template>`
This code causes error: "Component template requires a root element, rather than just text."

**Comment by joostdelange** [comment]
Recently I encountered this one too. In order to fix this you have define an option to the plugin like this:
`plugins: [createVuePlugin({ vueTemplateOptions: { preprocessLang: 'pug' } })]`

**Comment by joostdelange** [comment]
I was maybe a bit too fast with my answer. Just noticed an open PR which addresses this problem #42

**Comment by underfin** [comment]
> This code causes error: "Component template requires a root element, rather than just text."

The vue2 need one root element for template block. That should be `<template lang="pug"> <div>p index </div></template>`.

> I use lang="pug" in my template.

It should work after https://github.com/underfin/vite-plugin-vue2/pull/42 merged.

**Comment by AKamion** [comment]
Thank you. With this option all works correctly.
