### ISSUE TITLE
Support for jsx?

### ISSUE THREAD

**Issue by Aaron-Pool** [underfin/vite-plugin-vue2#5]
I'm assuming that this won't handle jsx, since it relies on a Babel preset, is that correct?

**Comment by underfin** [comment]
Yeah.The `jsx` is not handled for now

**Comment by cdll** [comment]
but why is this issue been closed? waiting for jsx support too💪💪

**Comment by Aaron-Pool** [comment]
> but why is this issue been closed? waiting for jsx support too💪💪

He closed it because he implemented jsx support 👌
