### ISSUE TITLE
not working well for a starter-seed

### ISSUE THREAD

**Issue by cdll** [underfin/vite-plugin-vue2#6]
OS: macOS 10.15.5
nodejs: v12.16.1
---
after doing 
````shell
$ npm init vite-app demo
$ cd demo
$ npm i -S vue@2 vite-plugin-vue2
$ npm run dev
````
within putting these code into ``vite.config.js``
````js
const { createVuePlugin } = require('vite-plugin-vue2')

module.exports = {
  plugins: [
    createVuePlugin()
  ]
}

````

i got these errors:
````shell
> vite

vite v1.0.0-rc.4
[vite] Error: a local installation of `vue` is detected but no matching `@vue/compiler-sfc` is found. Make sure to install both and use the same version.
[vite] Optimizable dependencies detected:
vite-plugin-vue2

[vite] Dep optimization failed with error:
[vite]: Rollup failed to resolve import "react-dom/server" from "react-dom/server?commonjs-external".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`rollupInputOptions.external`
````

could anyone give some help?

**Comment by zhangyuang** [comment]
same error

**Comment by Rainmen-xia** [comment]
me too

**Comment by underfin** [comment]
I tested it, but get error is this rather than yours.It caused by `vite-plugin-vue2` should placed into `devDependencies` inside `package.json`.
```
[vite] Error: a local installation of `vue` is detected but no matching `@vue/compiler-sfc` is found. Make sure to install both and use the same version.
[vite] Optimizable dependencies detected:
vite-plugin-vue2

[vite] Dep optimization failed with error:
Dependency vite-plugin-vue2 is attempting to import Node built-in module path.
This will not work in a browser environment.
Imported by: node_modules/vite-plugin-vue2/dist/esbuildService.js
```
Anyone can provider one repo for this?

**Comment by zhangyuang** [comment]
https://github.com/zhangyuang/vite-vue2-error-repo
@underfin here is reproduction
![image](https://user-images.githubusercontent.com/17424434/91528814-c4f53280-e93a-11ea-9e35-59ab42fa0b24.png)

**Comment by underfin** [comment]
The `create-vite-app` is support vue3 by default.After install, you need update some fileds inside package.json.
```
 "dependencies": {},
  "devDependencies": {
    "vite": "^1.0.0-rc.1",
    "vite-plugin-vue2": "^0.1.3"
  }
```
@zhangyuang The error is happend by `vite` internal support vue3.The ` "dependencies": {
    "vue": "^2.6.12"
  },` is mislead detection for vue.So you can remove this as a workaround or ingore it, it will not break the dev server start.

**Comment by Rainmen-xia** [comment]
$ tnpm run serve

> vuejs-starterkit@1.0.0 serve /Users/xxx/dev/test/vuejs-starterkit
> vite

vite v1.0.0-rc.4
[vite] Error: a local installation of `vue` is detected but no matching `@vue/compiler-sfc` is found. Make sure to install both and use the same version.

  Dev server running at:
  > Local:    http://localhost:3000/
  > Network:  http://10.43.15.124:3000/



I can setup the porject .but still have the same error

**Comment by cdll** [comment]
works with ``"vue": "2.6.12"`` with setting ``"devDependencies"`` in ``package.json``.
thank u @underfin
