### ISSUE TITLE
use render function in vue2.x and vite2.x compiles fail

### ISSUE THREAD

**Issue by littlekie** [underfin/vite-plugin-vue2#67]
![image](https://user-images.githubusercontent.com/31177102/115810655-ddaddd80-a420-11eb-9749-62583e5ce0a6.png)
It compiles with errors in this way.

I don't know if I missed a JSX plugin that caused the problem.
But, be able to work  in vue2.x、webpack  environment .
Whether it was caused by a JSX plugin conflict？
I try to fix it.

**Comment by levelyu** [comment]
> ![image](https://user-images.githubusercontent.com/31177102/115810655-ddaddd80-a420-11eb-9749-62583e5ce0a6.png)
> It compiles with errors in this way.
> 
> I don't know if I missed a JSX plugin that caused the problem.
> But, be able to work in vue2.x、webpack environment .
> Whether it was caused by a JSX plugin conflict？
> I try to fixe it.

I also encountered the same problem。i also set jsx to true, but it does not take effect and still reports an error

**Comment by jy0529** [comment]
You can try to set the jsx to true and use <script lang="jsx"> in SFC.

**Comment by littlekie** [comment]
> Please have a try with @jy0529 said.

Thank you! 
But,i think we need vite-loader or plugins to resolve the problem

**Comment by underfin** [comment]
I'm not sure the reason it worked fine at webpack, maybe you add jsx plugin to resolve it. But if you want use jsx, you should give specifc extension for it, else it will treact it as js and not transfromed by this plugin.
