### ISSUE TITLE
Incorrect source maps

### ISSUE THREAD

**Issue by Djaler** [underfin/vite-plugin-vue2#70]
For example, I have this SFC:
```
<template>
    <div>
        <template v-for="item in transformedItems">
            <template v-if="isSubmenu(item)">
                <Menu :key="item.title" :menu="item"/>
            </template>
            <template v-else>
                <MainMenuLink :key="item.title" :item="item"/>
            </template>
        </template>
    </div>
</template>

<script lang="ts">
    import { defineComponent } from '@vue/composition-api';

    import MainMenuLink from '@/components/menu-bar/main-menu-link/MainMenuLink.vue';
    import { isSubmenu } from '@/types/menu';

    import Menu from './Menu.vue';
    import { transformMenuTree } from './transform';

    export default defineComponent({
        name: 'MainMenu',
        components: { MainMenuLink, Menu },
        props: {
            items: {
                type: Array,
                required: true,
            },
        },
        setup(props) {
            const transformedItems = transformMenuTree(props.items, () => {
                debugger;
                return true;
            }, false);

            return {
                transformedItems,
                isSubmenu,
            };
        },
    });
</script>
```

As you can see, I have a debugger statement on line 34.

If I run this in dev server, I'll get this:
![Screenshot_20210429_114401](https://user-images.githubusercontent.com/7964583/116524557-32999a00-a8e0-11eb-82f2-88dd7ca07f62.png)

If I change script from ts to js, I'll get this:
![Screenshot_20210429_114504](https://user-images.githubusercontent.com/7964583/116524688-578e0d00-a8e0-11eb-9728-94a22fd89e8f.png)
This isn't correct too, but better then with ts.

**Comment by underfin** [comment]
I fixed location of debugger for ts, but not reproduct for js. Please clear cache and have a try with js, if you also have issue, please provider a reproduction to let me can track it.

**Comment by Djaler** [comment]
Yeah, now it works for ts as same as for js.
Looks like the `+1 LOC` issue is caused by vite-plugin-components. Will investigate this, thanks!
