### ISSUE TITLE
vite-plugin-vue2 & @vitejs/plugin-vue handle html "enter" char in browser has different

### ISSUE THREAD

**Issue by qwfy5287** [underfin/vite-plugin-vue2#73]
## example 1
```html
<span>aa</span>
<span>bb</span>
```

## example 2
```html
<span>aa</span><span>bb</span>
```

##  in Browser
@vitejs/plugin-vue all example not margin
vite-plugin-vue2    example 1 has margin

reproduction 
```
https://github.com/qwfy5287/vite-vue2-enter
```

**Comment by underfin** [comment]
fixed at https://github.com/underfin/vite-plugin-vue2/pull/62
