### ISSUE TITLE
vue-template-compiler's version mismatch

### ISSUE THREAD

**Issue by huih99** [underfin/vite-plugin-vue2#76]
I updated the latest vite-plugin-vue2@1.5.1 and found this error when I started the project

![image](https://user-images.githubusercontent.com/36914167/117775511-2b25a980-b26d-11eb-9226-f12df4952e1d.png)

in my project, the vue and vue-template-compiler version is specified as 2.5.17

my package.json
```json
dependencies: {
    "vue": "^2.5.17"
}
devDependencies: {
    "vue-template-compiler": "^2.5.17"
}
```

and the vite-plugin-vue2@1.5.1 package.json

```json
dependencies: {
    "vue-template-compiler": "^2.6.11"
}
```

I think this vue-template-compiler should not be specified in dependencies, it should be in PeerDependencies and use an earlier version number to match the version installed in the project

**Comment by underfin** [comment]
Hi @huih99, since https://github.com/underfin/vite-plugin-vue2/issues/86 to fix. I add a `vueTemplateCompiler` option, you can use it to avoid this case error.

**Comment by IndexXuan** [comment]
how to fixed this. v1.6.2 give mismatch errors again. why vue-template-compiler is dep instead of peerDeps ???
