### ISSUE TITLE
使用jsx报错

### ISSUE THREAD

**Issue by txw2018** [underfin/vite-plugin-vue2#94]
![image](https://user-images.githubusercontent.com/37097875/122179603-42823300-ceba-11eb-9d7e-f8aed9a1ab0b.png)
![image](https://user-images.githubusercontent.com/37097875/122179629-49a94100-ceba-11eb-8897-eceeda944b6a.png)
![image](https://user-images.githubusercontent.com/37097875/122179721-5d54a780-ceba-11eb-8a20-d70924e4fde4.png)

**Comment by underfin** [comment]
Can you give this example code to let me track it?

**Comment by sdvcrx** [comment]
@underfin 
Same here. But delete `babel.config.js` (vue-cli generated) can resolve this error.

Reproduction steps:

```bash
git clone https://github.com/underfin/vite-plugin-vue2
cd vite-plugin-vue2/playground
yarn add -D @vue/cli-plugin-babel   # simulate vue-cli generated project

cat <<EOF > babel.config.js
module.exports = {
  presets: [
    '@vue/cli-plugin-babel/preset'
  ]
}
EOF

# start vite
```

**Comment by underfin** [comment]
Fixed at https://github.com/underfin/vite-plugin-vue2/pull/78, please upgrade new version.

**Comment by vxhly** [comment]
一样的问题 ，我的 babel.config.js 配置

``` js
const IS_PROD = ['production', 'prod'].includes(process.env.NODE_ENV)

const plugins = ['transform-vue-jsx']
if (IS_PROD) {
  // plugins.push('transform-remove-console')
}

// lazy load ant-design-vue
// if your use import on Demand, Use this code
// plugins.push(['import', {
//   'libraryName': 'ant-design-vue',
//   'libraryDirectory': 'es',
//   'style': true // `style: true` 会加载 less 文件
// }])

module.exports = {
  presets: [
    '@vue/cli-plugin-babel/preset',
    [
      '@babel/preset-env',
      {
        'useBuiltIns': 'entry',
        'corejs': 3
      }
    ]
  ],
  plugins
}

```

**Comment by vxhly** [comment]
好像知道了，<scirpt></script> 标签上要写 `lang="tsx"`, 但是为什么呢
