### ISSUE TITLE
v1.6.2, Vue packages version mismatch again.

### ISSUE THREAD

**Issue by IndexXuan** [underfin/vite-plugin-vue2#96]
Dont really know why vue-template-compiler is deps instead of peerDeps. It was fixed in v1.5.2.

![image](https://user-images.githubusercontent.com/6322673/122498050-07e6da80-d021-11eb-94c9-1beea9e0b902.png)

I can do nothing but use yarn resolution or always use latest vue and VTC(must remove my yarn.lock and install again)

Thanks a lot for help.

**Comment by IndexXuan** [comment]
each Vue 2 project should have VTC installed. can we peerDeps?

**Comment by huih99** [comment]
@IndexXuan 作者这个更改compiler 版本的功能确实有点问题，我刚升级了试了下，原因在于`vue-template-compiler`这个包在导入时就会先检测版本是否匹配，而不是在使用时才检测。作者导入了一个默认版本用于在options中没有指定`vue-template-compiler`时回退使用，就会导致这个错误

**Comment by underfin** [comment]
嗯嗯应该放在 peerDependencies，我进行了回滚发布了新版本
